# APPLICATION
spring.application.name=Farm Management System
server.port=${PORT:8080}

# DATABASE
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.nbhbfvbmwglqypiwuvzf}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Yusuph123456789$@}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# THYMELEAF
spring.thymeleaf.cache=true
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# FILE UPLOAD
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# WEATHER API
weather.api.key=${WEATHER_API_KEY:8349e30b62205797ffa3fd1f912e560e}
weather.api.url=https://api.openweathermap.org/data/2.5/weather

# EMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:y99915369@gmail.com}
spring.mail.password=${MAIL_PASSWORD:lqipinjhedvymjca}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
app.email.from=${MAIL_USERNAME:y99915369@gmail.com}
app.email.admin=yusuphsaalim@gmail.com

# STATIC RESOURCES
spring.web.resources.cache.period=86400
spring.web.resources.chain.strategy.content.enabled=true
spring.web.resources.chain.strategy.content.paths=/**